### ISSUE TITLE
Missing LICENSE and README

### ISSUE THREAD

**Issue by TechnologyClassroom** [VayuDev/ledmatrix_pico#1]
I see an spdx identifier for a BSD.  You should add a LICENSE file to the root of the directory and GitHub will walk you through the steps to add the license to make it clear at a glance to all visitors.

You should copy and paste what you wrote for your [reddit post](https://reddit.com/r/raspberry_pi/comments/r7v4xo/raspberry_pi_pico_driving_64x32_ledmatrix_over/) into a README and add images or at the very least link to the post.

**Comment by VayuDev** [comment]
Sorry for only noticing you now, I had notifications disabled - I added the LICENSE file and linked to the reddit post. Thank you for bringing this to my attention!
